config/routes.rb
Rails.application.routes.draw do
  root 'zones#index'

  resources :zones do
    resources :sprinkles, shallow: true
  end

  resources :schedules
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :zone
end

app/models/sprinkle.rb
class Sprinkle < ActiveRecord::Base
  belongs_to :zone

  scope :active, -> { where("sprinkles.ends_at > ?", Time.now)}

  def duration=(seconds)
    self.ends_at = seconds.to_i.seconds.from_now
  end

  def duration
    if ends_at.nil?
      30
    else
      return ends_at - Time.now
    end
  end

  def remaining
    ends_at - Time.now
  end
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  has_many :sprinkles

  def closing_at
    active_sprinkles = sprinkles.active
    return unless active_sprinkles.any?
    will_close_at = nil
    active_sprinkles.each do |s|
      if will_close_at.nil? || s.ends_at > will_close_at
        will_close_at = s.ends_at
      end
    end

    will_close_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def signed_in?
    !current_user.nil?
  end

  def current_user
    warden.user
  end

  protected

  def osmosis
    env['osmosis']
  end

  def warden
    env['warden']
  end
end

app/controllers/sprinkles_controller.rb
class SprinklesController < ApplicationController
  def create
    @sprinkle = zone.sprinkles.create! sprinkle_params
    cmd = {
      action: {
        name: "open",
        id: @sprinkle.zone.gpio
      }
    }
    osmosis.dispatch JSON.generate(cmd)

    respond_to do |format|
      format.html
      format.js do
        render nothing: true
      end
    end
  end

  def destroy
    @sprinkle = Sprinkle.find(params[:id])
    @sprinkle.ends_at = Time.now
    @sprinkle.save!
    cmd = {
      action: {
        name: "close",
        id: @sprinkle.zone.gpio
      }
    }
    osmosis.dispatch JSON.generate(cmd)
    respond_to do |format|
      format.html
      format.js do
        render nothing: true
      end
    end
  end

  protected

  def sprinkle_params
    params.require(:sprinkle).permit(:duration)
  end

  def zone
    @zone ||= begin
      Zone.find(params[:zone_id])
    end
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    @zones = Zone.all
    render 'onboarding' and return if @zones.count == 0
  end

  def create
    @zone = Zone.create(zone_params)
    redirect_to :root
  end

  def edit
    @zone = Zone.find(params[:id])
  end

  def update
    @zone = Zone.find(params[:id])
    @zone.update zone_params
    redirect_to :zones
  end

  protected

  def zone_params
    params.require(:zone).permit(:name, :gpio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= content_tag :title, t('title') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= content_tag :main, class: [controller_name, action_name], as: "Listener" do %>
  <%= yield %>
<% end %>

</body>
</html>

app/views/layouts/application.js.erb
(function(target) {
  var e = new Event('<%= "#{controller_name}:#{action_name}" %>', {bubbles: true})
  <%= yield %>
})

app/views/sprinkles/_form.html.erb
<%= form_for [zone, zone.sprinkles.build], builder: SprinkleBuilder, remote: true, html: {class: %w(sprinkle) } do |f| %>
  <div class="action">
    <%= f.submit 'Ouvrir pour' %>
    <%= f.duration %>
  </div>
<% end %>

app/views/zones/_form.html.erb
<%= form_for zone, builder: ZoneBuilder do |f| %>
  <%= f.text_field :name, placeholder: t('zones.form.name') %>
  <%= f.gpio %>
  <%= f.button t('zones.form.button') %>
<% end %>

app/views/zones/edit.html.erb
<%= content_tag :h1, t('zones.edit.header') %>

<%= render 'form', zone: @zone %>

app/views/zones/index.html.erb
<h1>Zones</h1>

<section class="zones">
  <ul>
    <%= decorate @zones, :list %>
  </ul>
</section>

<%= link_to "Créer une nouvelle zone", new_zone_path, class: %w(new zone) %>

app/views/zones/new.html.erb
<%= content_tag :h1, t('zones.new.header') %>

<%= render 'form', zone: Zone.new %>

app/views/zones/onboarding.html.erb
<section class='onboarding'>
  <%= content_tag :h1, t('zones.onboarding.header') %>
  <p><%= link_to t('zones.link.new'), new_zone_path, class: %w(button) %></p>
</section>